### ISSUE TITLE
editor.openmaptiles.org is outdated

### ISSUE THREAD

**Issue by pathmapper** [openmaptiles/www.openmaptiles.org#28]
The Maputnik instance of `editor.openmaptiles.org`, which is linked here
https://openmaptiles.org/docs/style/maputnik/
and here
https://openmaptiles.org/styles/
is outdated, there are newer releases:
https://github.com/maputnik/editor/releases

Sometimes there are also questions about differences between `maputnik.github.io/editor/` and `editor.openmaptiles.org`:
https://github.com/maputnik/editor/issues/164#issuecomment-336253265
https://github.com/maputnik/editor/issues/177#issuecomment-337403168

What are the reasons for hosting an own instance of Maputnik? Maybe they could be adressed in another way, so that it would be OK for you to link to https://maputnik.github.io/editor instead?

**Comment by daliborjanak** [comment]
We have to decide what to do (minimally update). We will let you know. We have also customised version in cloud.maptiler.com

**Comment by pathmapper** [comment]
All right, thanks @daliborjanak !

**Comment by pathmapper** [comment]
Another confusion about https://editor.openmaptiles.org/ and https://maputnik.github.io/editor/:
https://github.com/maputnik/editor/issues/552

**Comment by pathmapper** [comment]
OK, https://editor.openmaptiles.org/ now redirects to https://cloud.maptiler.com/customize/, closing here.
