### ISSUE TITLE
Source code for self hosting server?

### ISSUE THREAD

**Issue by traverseda** [openmaptiles/www.openmaptiles.org#36]
The website says "Open-source maps made for self-hosting", but I can't find the source code for your "openmaptiles-server" application. Is that available somewhere?

**Comment by daliborjanak** [comment]
It's just packed TileServer GL to docker 
https://github.com/klokantech/tileserver-gl

**Comment by traverseda** [comment]
Awesome. I found that point pretty unclear, personally.
