### ISSUE TITLE
russian federation too big

### ISSUE THREAD

**Issue by chikashimiyama** [openmaptiles/www.openmaptiles.org#7]
I found russian federation under city section of the download page and the size is over 24GB. 
Probably it is a mistake.

![screen shot 2017-01-19 at 18 05 57](https://cloud.githubusercontent.com/assets/3512188/22116805/f8ceb572-de71-11e6-84d0-5101743ee76c.png)

**Comment by klokan** [comment]
Thanks for reporting @chikashimiyama 

@keosak - this is an extract hierarchy issue. Can we fix it please?

**Comment by keosak** [comment]
We had both Russia and Russian Federation, and that caused the problem. I unified them as Russian Federation.
