### ISSUE TITLE
Migration to MapLibre GL

### ISSUE THREAD

**Issue by webberig** [openmaptiles/www.openmaptiles.org#70]
As you may or may not already know, MapBox GL JS has recently updated to 2.0 and has moved to a non-OSS license.

Source: https://github.com/mapbox/mapbox-gl-js/issues/10162

Their pricing policy has changed so an access token is always required and the account gets charged based on map instance loads, not just requests to their API's. This would mean that you would still have to pay MapBox for using their library, even when self-hosting a tile server with openmaptiles sources. This makes using MapBox GL far less desirable combined with openmaptiles.

An opensource fork has risen and has been rebranded to [MapLibre](https://www.maplibre.org). I think it would be beneficial for both parties to to update the openmaptiles website and start using their name and demos, replacing all MapBox GL references.

I'm willing to make this change, and was actualy getting started, but I'm having trouble getting the website to run locally on my machine. I intalled Jekyll, but when I run `jekyll serve` I get following error:

```
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'base.scss':
                    Error: File to import not found or unreadable: _reset. on line 1:1 of base.scss >> @import "_reset"; ^
```

**Comment by daliborjanak** [comment]
Yes, we will be happy if you will update the site with MapLibre :+1: 

About the problem: You need to also clone git submodules so please run 
```
submodule init
submodule update
```
in the root of the website or clone it recursively with flag ```--recursive```
